# Generated by Django 5.1.8 on 2025-04-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
