# Generated by Django 5.1.8 on 2025-04-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_app', '0002_bomitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='custom_item_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='item_type',
            field=models.CharField(choices=[('material', 'Material'), ('labour', 'Labour'), ('other', 'Other')], max_length=50),
        ),
    ]
